data_dir: &DIR ../data/tweets-la-10k/

# preprocessing
raw_data_file: /Users/chao/data/source/tweets-la-10k/clean/tweets.txt
grid_list: [50, 50]
train_ratio: 0.7
valid_ratio: 0.1
min_token_freq: 10

# training
train_data_file: !join [*DIR, input/train.txt]
test_data_file: !join [*DIR, input/test.txt]
valid_data_file: !join [*DIR, input/test.txt]
x_vocab_file: !join [*DIR, input/words.txt]
y_vocab_file: !join [*DIR, input/locations.txt]
train_log_file: !join [*DIR, output/train_log.txt]
performance_file:  !join [*DIR, output/performance.txt]
model_path: !join [*DIR, model/]
case_seed_file: !join [*DIR, input/case_seeds.txt]
case_output_file: !join [*DIR, output/case_outputs.txt]

classify_train_file: !join [*DIR, input/classify_train.txt]
classify_test_file: !join [*DIR, input/classify_test.txt]
classify_cat_file: !join [*DIR, input/classify_category.txt]
classify_train_ratio: 0.8

load_model: False
save_model: True
data_worker: 4
n_sense: 2
embedding_dim: 100
batch_size: 32
n_epoch: 50
print_gap: 100
learning_rate: 0.002
K: 10


eval_dim: False
# dim_list: [2, 5, 10, 15, 20, 50, 100]
dim_list: [20, 80, 100, 150, 200]

eval_batch: False
batch_list: [32, 64, 128]

eval_lr: False
lr_list: [0.001, 0.002, 0.003, 0.004, 0.005, 0.01]

eval_sense: False
n_sense_list: [1,2,3,4,5,6,7,8,9,10]

# model_type_list: ['recon', 'attn', 'sense', 'attn_sense', 'comp_attn_sense', 'bilinear_sense', 'bidirection_sense']
# model_type_list: ['recon', 'attn', 'sense', 'attn_sense', 'comp_attn_sense', 'bilinear_sense']
model_type_list: ['recon', 'comp_attn_sense']
# model_type_list: ['recon']
# model_type_list: ['recon', 'sense', 'comp_attn_sense', 'bilinear_sense']
# model_type_list: ['sense', 'comp_attn_sense', 'bilinear_sense']
# model_type_list: ['sense']

