data_dir: &DIR ../data/tweets-la-10k/

# preprocessing
raw_data_file: /Users/chao/data/source/tweets-la-10k/clean/tweets.txt
grid_list: [50, 50]
train_ratio: 0.7
valid_ratio: 0.1
min_token_freq: 10
classify_train_ratio: 0.8

load_pretrained: False
load_model: False
data_worker: 4
n_sense: 2
embedding_dim: 50
batch_size: 64
n_epoch: 5
learning_rate: 0.005
regu_strength: 0
dropout: 0

eval_dim: False
dim_list: [25, 50, 100, 200, 150, 400]
eval_batch: False
batch_list: [8, 16, 64]
eval_lr: False
lr_list: [0.002, 0.008, 0.01]
eval_sense: False
n_sense_list: [3,4,5]
eval_dp: True
dp_list: [0.1, 0.5]
eval_regu: True
regu_list: [0.00001, 0.0001, 0.001, 0.01, 0.1]

model_type_list: ['recon', 'sense']
cmp_model_type_list: ['recon', 'sense']
