data_dir: &DIR ../data/tweets-1m/

# preprocessing
raw_data_file: /shared/data/czhang82/source/tweets-www/clean/tweets.txt
grid_list: [100, 100]
train_ratio: 0.8
valid_ratio: 0.1
min_token_freq: 50
classify_train_ratio: 0.8

load_pretrained: False
load_model: False
data_worker: 8
n_sense: 2
embedding_dim: 100
batch_size: 1024
n_epoch: 10
learning_rate: 0.005
regu_strength: 0
dropout: 0

eval_dim: False
dim_list: [300, 400, 50]
eval_batch: False
batch_list: [2048, 4096]
eval_lr: False
lr_list: [0.001, 0.002, 0.003, 0.004, 0.01]
eval_sense: False
n_sense_list: [3,4,5]
eval_dp: True
dp_list: [0.1, 0.5]
eval_regu: True
regu_list: [0.00001, 0.0001, 0.001, 0.01, 0.1]

model_type_list: ['sense']
cmp_model_type_list: ['recon', 'sense']
